<?php

declare(strict_types=1);

namespace Idiosyncratic\Spiral\EventSauceBridge;

use RuntimeException;
use Spiral\Boot\DirectoriesInterface;

use function is_dir;
use function is_writable;
use function sprintf;

final class AggregateRootRepositoryFactory
{
    private const string REPOSITORY_CLASS_TEMPLATE = <<<'EOPHP'
<?php

namespace <namespace>;

use EventSauce\EventSourcing\AggregateRootRepository;
use EventSauce\EventSourcing\EventSourcedAggregateRootRepository;

/**
 * AUTOGENERATED CLASS - DO NOT EDIT
 */
class <className> extends EventSourcedAggregateRootRepository implements AggregateRootRepository
{
}

EOPHP;

    private string $repositoryDirectory;

    public function __construct(
        private readonly DirectoriesInterface $dirs
    ) {
        $this->repositoryDirectory = sprintf('%s/repository_classes', $this->dirs->get('runtime'));

        if (
            is_dir($this->repositoryDirectory) === false
        ) {
            mkdir($this->repositoryDirectory);
        }
    }

    public function generateRepositoryClass() : void
    {
    }
}
