<?php

declare(strict_types=1);

namespace Idiosyncratic\Spiral\EventSauceBridge;

use Spiral\Boot\DirectoriesInterface;

use function array_pop;
use function array_reduce;
use function chmod;
use function class_exists;
use function explode;
use function file_put_contents;
use function implode;
use function is_dir;
use function mkdir;
use function sprintf;
use function str_replace;

use const PHP_EOL;

final class AggregateRootRepositoryFactory
{
    private const string REPOSITORY_CLASS_TEMPLATE = <<<'EOPHP'
        <?php

        namespace <namespace>;

        use EventSauce\EventSourcing\EventSourcedAggregateRootRepository;
        use EventSauce\EventSourcing\AggregateRootRepository;
        use EventSauce\EventSourcing\AggregateRootId;
        use EventSauce\EventSourcing\ClassNameInflector;
        use EventSauce\EventSourcing\MessageDecorator;
        use EventSauce\EventSourcing\MessageDispatcher;
        use EventSauce\EventSourcing\MessageRepository;
        use Idiosyncratic\Spiral\EventSauceBridge\Attribute\AggregateRootRepository as AggregateRootRepositoryAttribute;
        use Idiosyncratic\Spiral\EventSauceBridge\Attribute\MessageRepositoryTable;
        use Idiosyncratic\Spiral\EventSauceBridge\Attribute\MessageDecorator as MessageDecoratorAttribute;
        use Idiosyncratic\Spiral\EventSauceBridge\Attribute\MessageDispatcher as MessageDispatcherAttribute;
        use Idiosyncratic\Spiral\EventSauceBridge\DeletableAggregateRoot;

        /**
         * AUTOGENERATED CLASS - DO NOT EDIT
         */
        class <className> extends EventSourcedAggregateRootRepository implements AggregateRootRepository
        {
            public function __construct(
                #[MessageRepositoryTable(table: '<messageTable>', database: '<database>', useOutbox: <useOutbox>, outboxTableName: '<outboxTableName>')]
                MessageRepository $messageRepository,
                <messageDecoratorParameter>
                ClassNameInflector $classNameInflector,
                <messageDispatcherParameter>
            ) {
                parent::__construct(
                    aggregateRootClassName: '\<aggregateFQCN>',
                    messageRepository: $messageRepository,
                    decorator:  $decorator,
                    classNameInflector: $classNameInflector,
                    dispatcher: $dispatcher,
                );
            }

            public function retrieve(
                AggregateRootId $aggregateRootId,
            ) : object {
                $aggregateRoot = parent::retrieve($aggregateRootId);

                if ($aggregateRoot->aggregateRootVersion() === 0) {
                    throw new DomainException(sprintf('AggregateRoot with id %s not found', $aggregateRootId->toString()));
                }

                if (
                    $aggregateRoot instanceof DeletableAggregateRoot &&
                    $aggregateRoot->isDeleted() === true
                ) {
                    throw new DomainException(sprintf('AggregateRoot with id %s not found', $aggregateRootId->toString()));
                }

                return $aggregateRoot;
            }
        }
        EOPHP;

    private string $generatedCodeDirectory;

    public function __construct(
        private readonly DirectoriesInterface $dirs,
    ) {
        $this->generatedCodeDirectory = sprintf('%srepository_classes', $this->dirs->get('runtime'));

        if (
            is_dir($this->generatedCodeDirectory) !== false
        ) {
            return;
        }

        mkdir($this->generatedCodeDirectory);
    }

    /**
     * @param array<string> $dispatchers
     * @param array<string> $decorators
     */
    public function generateRepositoryClass(
        string $namespace,
        string $repositoryClass,
        string $messageTable,
        string $database,
        string $aggregateFQCN,
        bool $useOutbox,
        string $outboxTableName,
        array $dispatchers,
        array $decorators,
    ) : void {
        if (class_exists($repositoryClass) === true) {
            return;
        }

        $path = explode('\\', $repositoryClass);

        $repositoryShortClass = array_pop($path);

        $classContent = self::REPOSITORY_CLASS_TEMPLATE;

        $classContent = array_reduce(
            [
                ['namespace', $namespace],
                ['className', $repositoryShortClass],
                ['messageTable', $messageTable],
                ['database', $database],
                ['aggregateFQCN', $aggregateFQCN],
                ['useOutbox', ($useOutbox ? 'true' : 'false')],
                ['outboxTableName', $outboxTableName],
                ['messageDispatcherParameter', $this->makeMessageDispatcherParameter($dispatchers)],
                ['messageDecoratorParameter', $this->makeMessageDecoratorParameter($decorators)],
            ],
            static function ($classContent, $token) {
                return str_replace(sprintf('<%s>', $token[0]), $token[1], $classContent);
            },
            $classContent,
        );

        $repositoryClassDirectory = sprintf(
            '%s/%s',
            $this->generatedCodeDirectory,
            implode('/', $path),
        );

        if (is_dir($repositoryClassDirectory) === false) {
            mkdir(directory: $repositoryClassDirectory, recursive: true, permissions: 0755);
        }

        $filename = sprintf('%s/%s.php', $repositoryClassDirectory, $repositoryShortClass);

        file_put_contents($filename, $classContent);

        chmod($filename, 0644);

        require $filename;
    }

    /** @param array<string> $decorators */
    private function makeMessageDecoratorParameter(
        array $decorators,
    ) : string {
        if (empty($decorators)) {
            return '        MessageDecorator $decorator,';
        }

        $paramLines = [];

        foreach ($decorators as $decorator) {
            $paramLines[] = sprintf('#[MessageDecoratorAttribute(\'%s\')]', $decorator);
        }

        $paramLines[] = 'MessageDecorator $decorator,';

        return implode(PHP_EOL . '        ', $paramLines);
    }

    /** @param array<string> $dispatchers */
    private function makeMessageDispatcherParameter(
        array $dispatchers,
    ) : string {
        if (empty($dispatchers)) {
            return '        MessageDispatcher $dispatcher,';
        }

        $paramLines = [];

        foreach ($dispatchers as $dispatcher) {
            $paramLines[] = sprintf('#[MessageDispatcherAttribute(\'%s\')]', $dispatcher);
        }

        $paramLines[] = 'MessageDispatcher $dispatcher,';

        return implode(PHP_EOL . '        ', $paramLines);
    }
}
